In [2]:
import tensorflow as tf
import numpy as np

# transpose, reshape, concat, split 

In [50]:
a = np.array(range(28)).reshape((-1,2))
print (a.shape)

a

(14, 2)


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27]])

In [45]:
t_a = tf.Variable(a)

In [46]:
sess = tf.InteractiveSession()
t_a.initializer.run()


In [49]:
a_s = tf.split(t_a, 2, axis=0)
print (len(a_s))
print (a_s[0].eval())
               

2
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]


In [54]:
a_c = tf.concat(a_s, 1)
print (a_c.eval())

[[ 0  1 14 15]
 [ 2  3 16 17]
 [ 4  5 18 19]
 [ 6  7 20 21]
 [ 8  9 22 23]
 [10 11 24 25]
 [12 13 26 27]]


In [58]:
a_r = tf.reshape(a_c, (-1, 2))
print ("shape:", a_r.shape, "\n", a_r.eval())

shape: (14, 2) 
 [[ 0  1]
 [14 15]
 [ 2  3]
 [16 17]
 [ 4  5]
 [18 19]
 [ 6  7]
 [20 21]
 [ 8  9]
 [22 23]
 [10 11]
 [24 25]
 [12 13]
 [26 27]]


In [67]:
b = tf.reshape(tf.Variable(np.array(range(8))), (2,4))
b.eval()

FailedPreconditionError: Attempting to use uninitialized value Variable_16
	 [[Node: Variable_16/read = Identity[T=DT_INT64, _class=["loc:@Variable_16"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_16)]]
	 [[Node: Variable_16/read/_17 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_4_Variable_16/read", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'Variable_16/read', defined at:
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-67-bf5b09e0e8ca>", line 1, in <module>
    b = tf.reshape(tf.Variable(np.array(range(8))), (2,4))
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 226, in __init__
    expected_shape=expected_shape)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 344, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1490, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/lizhang/.conda/envs/tf1.0/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value Variable_16
	 [[Node: Variable_16/read = Identity[T=DT_INT64, _class=["loc:@Variable_16"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_16)]]
	 [[Node: Variable_16/read/_17 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_4_Variable_16/read", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]


In [5]:
sess.close()